In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from sklearn import metrics
import scipy.stats
import warnings
warnings.filterwarnings('ignore')

In [54]:
pip install openpyxl


### Load the dataset and inspect the first five rows and the last five rows

In [87]:
cars = pd.read_excel("data\JijiCarsRawDataFinal.xlsx")
# check the first 5 rows
cars.head()

Model    Make   YOM   Color          Used Transmission      Mileage  \
0  X-Trail  Nissan  2014   Black  Foreign Used    Automatic       136000   
1    Teana  Nissan  2014  Silver  Foreign Used    Automatic        85000   
2    Teana  Nissan  2013    Gray  Foreign Used    Automatic        90231   
3  X-Trail  Nissan  2014   White  Foreign Used    Automatic        52000   
4     Note  Nissan  2014   White  Foreign Used    Automatic  Unavailable   

               Location          Price  
0        Nairobi, Karen  KSh 2,050,000  
1     Nairobi, Kilimani  KSh 1,380,000  
2    Nairobi, Ridgeways    KSh 995,000  
3      Nairobi, Jamhuri  KSh 2,500,000  
4  Mombasa, Mombasa CBD  KSh 1,100,000

In [88]:
# check the last 5 rows
cars.tail()

Model  Make   YOM  Color          Used Transmission      Mileage  \
46680  Romeo  Alfa  2015  Black  Foreign Used    Automatic  Unavailable   
46681  Romeo  Alfa  2016  White  Foreign Used    Automatic        75048   
46682  Romeo  Alfa  2002    Red   Kenyan Used    Automatic        72000   
46683  Romeo  Alfa  1992   Blue   Kenyan Used       Manual       150000   
46684  Romeo  Alfa  1987    Red   Kenyan Used       Manual  Unavailable   

                     Location          Price  
46680       Nairobi, Kilimani  KSh 1,800,000  
46681      Nairobi, Ridgeways  KSh 1,500,000  
46682      Nairobi, Westlands    KSh 289,000  
46683          Nairobi, Karen    KSh 300,000  
46684  Kajiado, Ongata Rongai     KSh 80,000

### Check

In [89]:
cars.keys()

Index(['Model', 'Make', 'YOM', 'Color', 'Used', 'Transmission', 'Mileage',
       'Location', 'Price'],
      dtype='object')

In [90]:
cars['Model'].unique()

array(['X-Trail', 'Teana', 'Note', 'Qashqai', 'Navara', 'March',
       'Skyline', 'Elgrand', 'Fuga', 'Lafesta', 'Sylphy', 'Juke', 'Latio',
       'Dayz', 'Tiida', 'Moco', 'NV3500', 'Pick-Up', 'Serena', 'Advan',
       'Murano', 'Cube', 'Dualis', 'Wingroad', 'Bluebird', 'Caravan',
       'Vanette', 'NP300', 'NV100', '200SX', 'Leaf', '260Z', 'XTrail',
       'Commercial', 'Sunny', '100', 'Altima', 'GT-R', 'Silvia', 'Patrol',
       'FB14', '350Z', 'Versa', 'Primera', 'Atlas', 'Hardbody',
       'Pathfinder', 'NV200', 'FB15', 'DoubleCab', 'Pulsar', 'Terrano',
       '1400', 'Liberty', 'Almera', 'Carina', 'Avenir', 'Pino', 'Titan',
       'Cabstar', 'UD', 'Otti', 'Prairie', '370Z', '240SX', '300ZX',
       '899,999', 'Micra', 'Cima', '620,000', 'Cefiro', 'Violet',
       'Cedric', 'Extrail', 'Forester', 'Outback', 'Legacy', 'Impreza',
       'Vivio', 'Levorg', 'XV', '787,500', 'SVX', 'Exiga', '1,124,998',
       'Trezia', '1.8', 'Pleo', '1600', '562,500', 'Tribeca', '843,750',
       '618

In [91]:
cars.drop('Model', axis=1, inplace=True)

In [92]:
cars['Make'].unique()

array(['Nissan', 'KSh', 'Subaru', 'Mazda', 'Mercedes-Benz', 'Toyota',
       'TOYOTA', nan, 'BMW', 'Bmw', 'Mitsubishi', 'Volkswagen', 'Audi',
       'Land Rover', 'Land', 'Suzuki', 'Honda', 'Lexus', 'Volvo',
       'Peugeot', 'Ford', 'Daihatsu', 'Jeep', 'Porsche', 'Chevrolet',
       'Hyundai', 'Jaguar', 'Mini', 'Kia', 'Alfa'], dtype=object)

In [93]:
cars.Make[cars.Make =='KSh'] ='NaN'
cars.dropna(subset = ['Make'], inplace=True)
cars.Make[cars.Make =='Bmw'] ='BMW'
cars.Make[cars.Make =='Toyota'] ='TOYOTA'
cars.Make[cars.Make =='Land'] ='Land Rover'

cars.Make.unique()

array(['Nissan', 'NaN', 'Subaru', 'Mazda', 'Mercedes-Benz', 'TOYOTA',
       'BMW', 'Mitsubishi', 'Volkswagen', 'Audi', 'Land Rover', 'Suzuki',
       'Honda', 'Lexus', 'Volvo', 'Peugeot', 'Ford', 'Daihatsu', 'Jeep',
       'Porsche', 'Chevrolet', 'Hyundai', 'Jaguar', 'Mini', 'Kia', 'Alfa'],
      dtype=object)

In [94]:
cars['Color'].unique()

array(['Black', 'Silver', 'Gray', 'White', 'Green', 'Brown', 'Purple',
       'Beige', 'Red', 'Pearl', 'Orange', 'Pink', '2014', 'Blue', 'Gold',
       '2012', 'Other', 'Yellow', 'Burgandy', '2013', 'Teal', 'white',
       'Premium', '2015', 'SV', 'Ivory', '2002', '2006', '1.4', '2011',
       '2008', '899,999', '2004', '2.0', '1.2', '2009', '620,000', '2007',
       '1.8', 'Shape', '787,500', '1,124,998', 'Trend', '562,500',
       '843,750', '618,748', '3,352,500', '2010', '2,924,998',
       '1,237,500', '1,215,000', 'Package', '2,081,250', '1,293,750',
       '1,203,750', '2,925,000', '528,748', '2,249,998', '877,500',
       '2005', 'silver', '787,498', 'green', 'beige', 'black', 'blue',
       'red', '1,350,000', 'purple', 'gray', 'orange', '2016',
       '1,687,500', '2,362,500', 'AWD', '2,475,000', '618,750',
       '1,068,750', '956,250', '765,000', '742,498', '427,500', '337,500',
       '506,250', '450,000', '731,250', 'brown', '2,290,000', '2,306,248',
       '1,968,750', '

In [95]:
colors_mapping = {
    'black': 'Black',
    'silver': 'Silver',
    'gray': 'Gray',
    'white': 'White',
    'green': 'Green',
    'brown': 'Brown',
    'purple': 'Purple',
    'beige': 'Beige',
    'red': 'Red',
    'pearl': 'Pearl',
    'orange': 'Orange',
    'pink': 'Pink',
    'blue': 'Blue',
    'gold': 'Gold',
    'yellow': 'Yellow',
    'burgandy': 'Burgandy',
    'teal': 'Teal',
    'ivory': 'Ivory',
    'whte': 'White',  # Assuming 'whte' is a typo and should be 'white'
}

# Convert the 'Color' column to lowercase and map valid colors
cars['Color'] = cars['Color'].str.lower().map(colors_mapping)

# Display unique values in the cleaned 'Color' column
print(cars['Color'].unique())

['Black' 'Silver' 'Gray' 'White' 'Green' 'Brown' 'Purple' 'Beige' 'Red'
 'Pearl' 'Orange' 'Pink' nan 'Blue' 'Gold' 'Yellow' 'Burgandy' 'Teal'
 'Ivory']


In [96]:
# Drop rows with missing values in the 'Color' column
cars.dropna(subset=['Color'], inplace=True)

In [97]:
cars['Used'].unique()

array(['Foreign Used', 'Kenyan Used', 'Brand New', 'Automatic', 'Manual',
       '94871'], dtype=object)

In [98]:
cars['Used'].replace(('Manual', 'Automatic', 
       'km', 'Mombasa, Mombasa CBD', '94871'), float('NaN'),
                     inplace=True)
cars.dropna(subset = ['Used'], inplace=True)
cars.Used.unique()

array(['Foreign Used', 'Kenyan Used', 'Brand New'], dtype=object)

In [99]:
cars['Transmission'].unique()

array(['Automatic', 'Manual', 'CVT', 'AMT'], dtype=object)

In [100]:
cars.Mileage.unique()

array([136000, 85000, 90231, ..., 117590, 100144, 75048], dtype=object)

In [101]:
# Use describe to get summary statistics
mileage_summary = cars['Mileage'].describe()

# Print the summary statistics
print(mileage_summary)

count           45147
unique          10525
top       Unavailable
freq             8103
Name: Mileage, dtype: object


In [102]:
cars['Mileage'] = cars['Mileage'].replace('...', pd.NA, regex=False)
cars.Mileage.unique()

array([136000, 85000, 90231, ..., 117590, 100144, 75048], dtype=object)

In [103]:
# Convert the 'Mileage' column to numeric, excluding 'Unavailable' values
cars['Mileage'] = pd.to_numeric(cars['Mileage'], errors='coerce')

# Replace 'Unavailable' with the median of numeric values
cars['Mileage'].replace('Unavailable', cars['Mileage'].median(), inplace=True)

In [104]:
# Check if 'Unavailable' is present in the 'Mileage' column
unavailable_check = 'Unavailable' in cars['Mileage'].values

# Print the result
print("Is 'Unavailable' present in the Mileage column?", unavailable_check)

Is 'Unavailable' present in the Mileage column? False


In [105]:
# Calculate the median of the 'Mileage' column
median_mileage = cars['Mileage'].median()

# Fill missing values in the 'Mileage' column with the median
cars['Mileage'].fillna(median_mileage, inplace=True)


In [106]:
cars.Location.unique()

array(['Nairobi, Karen', 'Nairobi, Kilimani', 'Nairobi, Ridgeways',
       'Nairobi, Jamhuri', 'Mombasa, Mombasa CBD',
       'Nairobi, Nairobi Central', 'Mombasa, Mvita',
       'Mombasa, Kizingo / Mombasa', 'Nairobi, Lavington',
       'Mombasa, Tudor', 'Kiambu, Kiambu / Kiambu', 'Nairobi, Muthaiga',
       'Mombasa, Ganjoni', 'Nairobi, Parklands/Highridge',
       'Nairobi, South C', 'Nairobi, Dagoretti', 'Nairobi, Langata',
       'Mombasa, Kisauni', 'Nairobi, Kasarani', 'Nairobi, Westlands',
       'Kiambu, Ruaka', 'Kiambu, Githunguri', 'Mombasa, Tononoka',
       'Mombasa, Shimanzi', 'Mombasa, Changamwe', 'Nairobi, Mombasa Road',
       'Mombasa, Mbaraki', 'Nairobi', 'Kiambu, Juja', 'Nairobi, Pangani',
       'Machakos, Athi River', 'Nairobi, Thome / Nairobi',
       'Nyeri, Karatina Town', 'Uasin Gishu, Eldoret CBD',
       'Nairobi, Roysambu', 'Nairobi, Industrial Area Nairobi',
       'Mombasa, Nyali', 'Nairobi, Runda', 'Nairobi, Nairobi West',
       'Nakuru, Nakuru Town East

In [107]:
# Split the 'Location' column into 'City' and 'Area' columns
cars[['City', 'Area']] = cars['Location'].str.split(',', expand=True)

# Display the first few rows of the new columns along with the original 'Location' column for verification
cars[['Location', 'City', 'Area']].head()

Location     City          Area
0        Nairobi, Karen  Nairobi         Karen
1     Nairobi, Kilimani  Nairobi      Kilimani
2    Nairobi, Ridgeways  Nairobi     Ridgeways
3      Nairobi, Jamhuri  Nairobi       Jamhuri
4  Mombasa, Mombasa CBD  Mombasa   Mombasa CBD

In [75]:
# cars.drop('Location', axis=1, inplace=True)

In [108]:
# assuming your DataFrame is named 'cars' and the 'Price' column contains 'KSh' and commas
price_column = ['Price']
for column in price_column:
    cars[column] = cars[column].replace({'KSh': '', ',': ''}, regex=True)
    
print(cars.head())

     Make   YOM   Color          Used Transmission   Mileage  \
0  Nissan  2014   Black  Foreign Used    Automatic  136000.0   
1  Nissan  2014  Silver  Foreign Used    Automatic   85000.0   
2  Nissan  2013    Gray  Foreign Used    Automatic   90231.0   
3  Nissan  2014   White  Foreign Used    Automatic   52000.0   
4  Nissan  2014   White  Foreign Used    Automatic   86532.0   

               Location     Price     City          Area  
0        Nairobi, Karen   2050000  Nairobi         Karen  
1     Nairobi, Kilimani   1380000  Nairobi      Kilimani  
2    Nairobi, Ridgeways    995000  Nairobi     Ridgeways  
3      Nairobi, Jamhuri   2500000  Nairobi       Jamhuri  
4  Mombasa, Mombasa CBD   1100000  Mombasa   Mombasa CBD  


In [109]:
cars['Price'] = cars['Price'].astype(str).astype(str)
cars['Price'] = cars['Price'].str.replace('^\D*$', '', regex=True)

cars.Price.unique()

array([' 2050000', ' 1380000', ' 995000', ..., ' 4320000', ' 2787000',
       ' 289000'], dtype=object)

In [110]:
cars.YOM.unique()

array([2014, 2013, 2015, 1978, 2012, 2007, 2005, 1994, 2011, 2017, 2018,
       1990, 2003, 2008, 1987, 2016, 2010, 2009, 1966, 2000, 1991, 2004,
       1996, 1998, 2006, 1997, 2001, 2002, 1981, 1999, 1986, 1995, 1992,
       1985, 1993, 1988, 1989, 2019, 1984, 1975, 2020, 1980, 1977, 1982,
       2021, 1965, 1979, 1976, 1973, 1967, 1963, 1968, 1983, 1961, 1972,
       1957], dtype=object)

In [111]:
# replace unknown with NaN
cars.YOM[cars.YOM =='Unkown'] ='NaN'
cars.YOM.unique()

array([2014, 2013, 2015, 1978, 2012, 2007, 2005, 1994, 2011, 2017, 2018,
       1990, 2003, 2008, 1987, 2016, 2010, 2009, 1966, 2000, 1991, 2004,
       1996, 1998, 2006, 1997, 2001, 2002, 1981, 1999, 1986, 1995, 1992,
       1985, 1993, 1988, 1989, 2019, 1984, 1975, 2020, 1980, 1977, 1982,
       2021, 1965, 1979, 1976, 1973, 1967, 1963, 1968, 1983, 1961, 1972,
       1957], dtype=object)

In [112]:
cars.isnull().sum()

Make              0
YOM               0
Color             0
Used              0
Transmission      0
Mileage           0
Location          0
Price             0
City              0
Area            326
dtype: int64

In [81]:
# Save the cleaned DataFrame to a CSV file
cars.to_csv('data\cleaned_cars.csv', index=False)